### ISSUE TITLE
EPIC: Player mechanics Part2: Twig controls

### ISSUE THREAD

**Issue by NuMellow** [NuMellow/lifeofanadventurer#15]
Twig follows the player and can be used to fend off creatures, help solve puzzles and of course be petted! Very important that the player can pet him!

- [x] Follows Player #16 
- [ ] Climb obstacles #25 
- [x] Stay #18 
- [x] Come #19 
- [ ] Attack #20 #21 
- [ ] Defend #22 
- [ ] Go to area of interest (maybe) #23 
- [ ] Pet! (Very important) #24

**Comment by NuMellow** [comment]
- [ ] Handle falling off the map #26
